### ISSUE TITLE
Too many certificate requests

### ISSUE THREAD

**Issue by ghost** [phovea/phovea_landing_page#7]
An unexpected error occurred:
There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for exact set of domains: caleydoapp.org,gapminder-retrieval.caleydoapp.org,gapminder.caleydoapp.org,lineage.caleydoapp.org,lineup.caleydoapp.org,malevo-daily.caleydoapp.org,malevo.caleydoapp.org,ordino-daily.caleydoapp.org,ordino-retrieval.caleydoapp.org,ordino.caleydoapp.org,pathfinder.caleydoapp.org,stratomex.caleydoapp.org,taco.caleydoapp.org,taggle-fusion.caleydoapp.org,taggle-outdated.caleydoapp.org,taggle.caleydoapp.org,thermalplot.caleydoapp.org,tourguide-daily.caleydoapp.org,tourguide-ordino.caleydoapp.org,vega-gapminder.caleydoapp.org: see https://letsencrypt.org/docs/rate-limits/

Please see the logfiles in /var/log/letsencrypt for more details.

**Comment by keckelt** [comment]
test

**Comment by keckelt** [comment]
I requested to many certificate duplicates while creating the forward for confusionflow.caleydoapp.org.
Duplicates because a certificate was requested  for the same (sub)domains.

> We also have a Duplicate Certificate limit of 5 certificates per week. A certificate is considered a duplicate of an earlier certificate if they contain the exact same set of hostnames, ignoring capitalization and ordering of hostnames. For instance, if you requested a certificate for the names [www.example.com, example.com], you could request four more certificates for [www.example.com, example.com] during the week. If you changed the set of names by adding [blog.example.com], you would be able to request additional certificates.

Source: https://letsencrypt.org/docs/rate-limits/

As a workaorund, confusionflow.caleydoapp.org is now defined as an app (PHOVEA_APP_CONFUSIONFLOW) that points to the same port as malevo-daily (in contrast to a simple forward (PHOVEA_FORWARD_CONFUSIONFLOW)).

**Comment by sgratzl** [comment]
see #2 

workaround -> register yet another domain cause the rate limit only applies to certificates with the exact same set
